// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4_aILkL3GE5-7AF4MCUMSLvF06w6E18',
    appId: '1:696649604846:web:5b69e64d46d6b302819dff',
    messagingSenderId: '696649604846',
    projectId: 'finance-management-4489c',
    authDomain: 'finance-management-4489c.firebaseapp.com',
    storageBucket: 'finance-management-4489c.firebasestorage.app',
    measurementId: 'G-79K1EDN7M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchAN0yNSrsMi8nuwyZHyZahP58an4JQA',
    appId: '1:696649604846:android:65ca2e38ef72f72e819dff',
    messagingSenderId: '696649604846',
    projectId: 'finance-management-4489c',
    storageBucket: 'finance-management-4489c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5OMMCZTPLRRZGMO3i7xrlYiZD5D6TBzM',
    appId: '1:696649604846:ios:401ddfc66c400618819dff',
    messagingSenderId: '696649604846',
    projectId: 'finance-management-4489c',
    storageBucket: 'finance-management-4489c.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5OMMCZTPLRRZGMO3i7xrlYiZD5D6TBzM',
    appId: '1:696649604846:ios:401ddfc66c400618819dff',
    messagingSenderId: '696649604846',
    projectId: 'finance-management-4489c',
    storageBucket: 'finance-management-4489c.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs4_aILkL3GE5-7AF4MCUMSLvF06w6E18',
    appId: '1:696649604846:web:bed68a40c3e026c7819dff',
    messagingSenderId: '696649604846',
    projectId: 'finance-management-4489c',
    authDomain: 'finance-management-4489c.firebaseapp.com',
    storageBucket: 'finance-management-4489c.firebasestorage.app',
    measurementId: 'G-KSN33839RB',
  );
}
